### PR TITLE
Requests can have additional record counts (EDNS)

### PR DESCRIPTION
**Pull request by Hakon**
Dig produces requests with additional record counts (part of EDNS). Is it OK to allow this?

### CODE REVIEW

**Comment by kapetan** [comment]
Thanks for the pull-request. Is it possible for you to generate a test fixture which actually contains an additional resource record? As far as I can see, Fixtures/Request/edns-test only has the additional count set to one in the header but does not contain an record in the body.

**Comment by Hakon** [comment]
The additional OPT record (type 41) is there, at the 11 last bytes.

**Comment by kapetan** [comment]
I'll soon release a new version with the changes. Thanks for the fixes.

**Comment by GF-Huang** [comment]
There may be a bug about EDNS caused by `Domain` class constructor.

 Because the `Domain` of `OPT RR` in EDNS **must** be `0`. 

If we use this code, we will get a `2` bytes array, this is not expected, we expect `1` byte array: `[ 0 ]`.

```c#
Domain.FromString(string.Empty).ToArray()
// got [ 0, 0 ]
```

The `Domain` constructor should be fixed by 
```c#
public Domain(string domain) : this(domain.Split('.', StringSplitOptions.RemoveEmptyEntries)) {}
```

Relative codes:

https://github.com/kapetan/dns/blob/d8f973cb31040b4c1b013defab437a53eab95995/DNS/Protocol/Domain.cs#L127C1-L129

https://github.com/kapetan/dns/blob/d8f973cb31040b4c1b013defab437a53eab95995/DNS/Protocol/ResourceRecords/ResourceRecord.cs#L91-L93

> [6.1.2](https://www.rfc-editor.org/rfc/rfc6891.html#section-6.1.2).  Wire Format
> 
>    An OPT RR has a fixed part and a variable set of options expressed as
>    {attribute, value} pairs.  The fixed part holds some DNS metadata,
>    and also a small collection of basic extension elements that we
>    expect to be so popular that it would be a waste of wire space to
>    encode them as {attribute, value} pairs.
> 
>    The fixed part of an OPT RR is structured as follows:
> 
>        +------------+--------------+------------------------------+
>        | Field Name | Field Type   | Description                  |
>        +------------+--------------+------------------------------+
>        | NAME       | domain name  | MUST be 0 (root domain)      |
>        | TYPE       | u_int16_t    | OPT (41)                     |
>        | CLASS      | u_int16_t    | requestor's UDP payload size |
>        | TTL        | u_int32_t    | extended RCODE and flags     |
>        | RDLEN      | u_int16_t    | length of all RDATA          |
>        | RDATA      | octet stream | {attribute,value} pairs      |
>        +------------+--------------+------------------------------+

**Pull request merged**
