### PR TITLE
Add ConfigureAwait(false)

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by kapetan** [comment]
Thanks for the addition

**Comment by codecat** [comment]
What's the purpose of this change? I'm running into issues with my async code due to this.

**Comment by NN---** [comment]
ConfigureAwait(false) doesn't preserve the synchronization context allowing code to be more efficient

https://devblogs.microsoft.com/dotnet/configureawait-faq/

What is the problem you have with this change ?

**Comment by codecat** [comment]
It seems my assumption about this was too rushed! I did some more testing and it turns out it was my code after all. My apologies 😺

**Pull request merged**
